import re
import subprocess
import os

configfile: "/projects/AusGEM/Users/Max/Manuscripts/ST95/snakemake/masterconfigs/masterconfig_ST95_all.yaml"

# Get assemblies
sample_ids, = glob_wildcards(config['assemblies']+"/{sample}.fasta")
prefix = config['prefix']

print(sample_ids)


rule all:
    input:
        #expand(config['outdir']+"/{prefix}/pointfinder/{sample}/{sample}_blastn_results_named.tsv", sample=sample_ids, prefix=prefix)
        config['outdir']+"/"+config['prefix']+"/pointfinder/Pointfinder.txt"
        #expand(config['outdir']+"{output_prefix}_abricate.tab", output_prefix = output_pre)

rule pointfinder_run:
    input:
        assembly = config['assemblies']+"/{sample}.fasta",
    output:
        config['outdir']+"/{prefix}/pointfinder/{sample}/{sample}_blastn_results.tsv"
    conda:
        "config/pointfinder.yaml"
    params:
        output_dir = config['outdir']+"/{prefix}/pointfinder/{sample}",
        species = config['pointfinder_species']
        #minid = config['minimum_id'],
        #mincov = config['minimum_cov']
    shell:
        """
        Pointfinder/PointFinder.py -i {input} -o {params.output_dir} -p Pointfinder/pointfinder_db {params.species} -m blastn -m_p /usr/local/ncbi-blast-ihpc-2.8.1+/bin/blastn
        """

rule name_append:
    input:
        config['outdir']+"/{prefix}/pointfinder/{sample}/{sample}_blastn_results.tsv"
    output:
        config['outdir']+"/{prefix}/pointfinder/{sample}/{sample}_blastn_results_named.tsv"
    shell:
        """awk 'NR == 1 {{print $0 "\tname_file"; next;}}{{print $0 "\t" FILENAME;}}' {input} > {output}"""


rule combine:
    threads:
        50
    input:
        expand(config['outdir']+"/{prefix}/pointfinder/{sample}/{sample}_blastn_results_named.tsv", sample=sample_ids, prefix=prefix)
    output:
        config['outdir']+"/{prefix}/pointfinder/Pointfinder_temp.txt"
    shell:
        """cat {input} > {output}"""

rule clean:
    input:
        config['outdir']+"/{prefix}/pointfinder/Pointfinder_temp.txt"
    output:
        config['outdir']+"/{prefix}/pointfinder/Pointfinder.txt"
    shell:
        """awk 'FNR==1 {{ header = $0; print }} $0 != header' {input} > {output}"""


# rule data_combine:
#	input:
#		config['outdir']+"{sample}/{sample}_blastn_results_named.tsv"
#	output:
#		config['outdir']+"{sample}.dummy_file"
#	params:
#		outfile = config['outdir']+"pointfinder.txt",
#	shell:
#		"""
#		touch {params.outfile}
#		awk 'NR == 1 {{print $0 "\tname_file"; next;}}{{print $0 "\t" FILENAME;}}' {input} >> {params.outdir}
#		touch {output}
#		"""
